# -*- coding: UTF-8 -*-
"""Localized labels for controls found during the public Suno audit."""

LABELS = {
	"af": (u"Terug na eenvoudige skepping", u"Maak stylopsies oop of toe", u"Genereer nuwe stylvoorstelle", u"Maak oudio-opsies oop of toe", u"Instrumentaal", u"Speel — {count} keer gespeel", u"Hou van — {count}"),
	"am": (u"ወደ ቀላል ፈጠራ ተመለስ", u"የቅጥ አማራጮችን ክፈት ወይም ዝጋ", u"አዲስ የቅጥ ጥቆማዎችን ፍጠር", u"የድምፅ አማራጮችን ክፈት ወይም ዝጋ", u"መሣሪያዊ", u"አጫውት — {count} ጊዜ", u"ወድጄዋለሁ — {count}"),
	"an": (u"Tornar ta la creyación simpla", u"Ubrir u zarrar as opcions d'estilo", u"Chenerar nuevas sucherencias d'estilo", u"Ubrir u zarrar as opcions d'audio", u"Instrumental", u"Reproducir — {count} reproduccions", u"Me fa goyo — {count}"),
	"ar": (u"العودة إلى الإنشاء البسيط", u"فتح أو إغلاق خيارات الأنماط", u"إنشاء اقتراحات أنماط جديدة", u"فتح أو إغلاق خيارات الصوت", u"موسيقى آلية", u"تشغيل — {count} مرات تشغيل", u"إعجاب — {count}"),
	"be": (u"Вярнуцца да простага стварэння", u"Адкрыць або закрыць параметры стыляў", u"Стварыць новыя прапановы стыляў", u"Адкрыць або закрыць параметры аўдыя", u"Інструментальная музыка", u"Прайграць — {count} прайграванняў", u"Падабаецца — {count}"),
	"bg": (u"Назад към лесното създаване", u"Отваряне или затваряне на опциите за стил", u"Генериране на нови предложения за стил", u"Отваряне или затваряне на аудио опциите", u"Инструментал", u"Възпроизвеждане — {count} пъти", u"Харесване — {count}"),
	"ca": (u"Torna a la creació senzilla", u"Obre o tanca les opcions d'estil", u"Genera suggeriments d'estil nous", u"Obre o tanca les opcions d'àudio", u"Instrumental", u"Reprodueix — {count} reproduccions", u"M'agrada — {count}"),
	"cs": (u"Zpět k jednoduchému vytvoření", u"Otevřít nebo zavřít možnosti stylů", u"Vygenerovat nové návrhy stylů", u"Otevřít nebo zavřít možnosti zvuku", u"Instrumentální", u"Přehrát — {count} přehrání", u"To se mi líbí — {count}"),
	"da": (u"Tilbage til enkel oprettelse", u"Åbn eller luk stilindstillinger", u"Generér nye stilforslag", u"Åbn eller luk lydindstillinger", u"Instrumental", u"Afspil — {count} afspilninger", u"Synes godt om — {count}"),
	"de": (u"Zurück zur einfachen Erstellung", u"Stiloptionen öffnen oder schließen", u"Neue Stilvorschläge erzeugen", u"Audiooptionen öffnen oder schließen", u"Instrumental", u"Abspielen — {count} Wiedergaben", u"Gefällt mir — {count}"),
	"el": (u"Επιστροφή στην απλή δημιουργία", u"Άνοιγμα ή κλείσιμο επιλογών στυλ", u"Δημιουργία νέων προτάσεων στυλ", u"Άνοιγμα ή κλείσιμο επιλογών ήχου", u"Οργανικό", u"Αναπαραγωγή — {count} αναπαραγωγές", u"Μου αρέσει — {count}"),
	"en": (u"Back to simple creation", u"Open or close style options", u"Generate new style suggestions", u"Open or close audio options", u"Instrumental", u"Play — {count} plays", u"Like — {count}"),
	"es": (u"Volver a la creación sencilla", u"Abrir o cerrar las opciones de estilo", u"Generar nuevas sugerencias de estilo", u"Abrir o cerrar las opciones de audio", u"Instrumental", u"Reproducir — {count} reproducciones", u"Me gusta — {count}"),
	"et": (u"Tagasi lihtsa loomise juurde", u"Ava või sulge stiilivalikud", u"Loo uusi stiilisoovitusi", u"Ava või sulge helivalikud", u"Instrumentaal", u"Esita — {count} esitust", u"Meeldib — {count}"),
	"eu": (u"Itzuli sorrera sinplera", u"Ireki edo itxi estilo-aukerak", u"Sortu estilo-iradokizun berriak", u"Ireki edo itxi audio-aukerak", u"Instrumentala", u"Erreproduzitu — {count} erreprodukzio", u"Atsegin dut — {count}"),
	"fa": (u"بازگشت به ساخت ساده", u"باز کردن یا بستن گزینه‌های سبک", u"ایجاد پیشنهادهای جدید سبک", u"باز کردن یا بستن گزینه‌های صدا", u"بی‌کلام", u"پخش — {count} بار", u"پسندیدن — {count}"),
	"fi": (u"Takaisin yksinkertaiseen luomiseen", u"Avaa tai sulje tyyliasetukset", u"Luo uusia tyyliehdotuksia", u"Avaa tai sulje ääniasetukset", u"Instrumentaali", u"Toista — {count} toistoa", u"Tykkää — {count}"),
	"fr": (u"Revenir à la création simple", u"Ouvrir ou fermer les options de style", u"Générer de nouvelles suggestions de style", u"Ouvrir ou fermer les options audio", u"Instrumental", u"Lire — {count} écoutes", u"J'aime — {count}"),
	"ga": (u"Ar ais chuig cruthú simplí", u"Oscail nó dún roghanna stíle", u"Gin moltaí nua stíle", u"Oscail nó dún roghanna fuaime", u"Uirlise", u"Seinn — {count} seinn", u"Is maith liom — {count}"),
	"gl": (u"Volver á creación sinxela", u"Abrir ou pechar as opcións de estilo", u"Xerar novas suxestións de estilo", u"Abrir ou pechar as opcións de audio", u"Instrumental", u"Reproducir — {count} reproducións", u"Gústame — {count}"),
	"he": (u"חזרה ליצירה פשוטה", u"פתיחה או סגירה של אפשרויות סגנון", u"יצירת הצעות סגנון חדשות", u"פתיחה או סגירה של אפשרויות שמע", u"אינסטרומנטלי", u"ניגון — {count} השמעות", u"אהבתי — {count}"),
	"hi": (u"सरल निर्माण पर वापस जाएँ", u"शैली विकल्प खोलें या बंद करें", u"नई शैली के सुझाव बनाएँ", u"ऑडियो विकल्प खोलें या बंद करें", u"वाद्य संगीत", u"चलाएँ — {count} बार", u"पसंद — {count}"),
	"hr": (u"Natrag na jednostavno stvaranje", u"Otvori ili zatvori mogućnosti stilova", u"Generiraj nove prijedloge stilova", u"Otvori ili zatvori mogućnosti zvuka", u"Instrumental", u"Reproduciraj — {count} reprodukcija", u"Sviđa mi se — {count}"),
	"hu": (u"Vissza az egyszerű létrehozáshoz", u"Stílusbeállítások megnyitása vagy bezárása", u"Új stílusjavaslatok létrehozása", u"Hangbeállítások megnyitása vagy bezárása", u"Instrumentális", u"Lejátszás — {count} lejátszás", u"Tetszik — {count}"),
	"id": (u"Kembali ke pembuatan sederhana", u"Buka atau tutup opsi gaya", u"Buat saran gaya baru", u"Buka atau tutup opsi audio", u"Instrumental", u"Putar — {count} pemutaran", u"Suka — {count}"),
	"is": (u"Til baka í einfalda gerð", u"Opna eða loka stílvalkostum", u"Búa til nýjar stíltillögur", u"Opna eða loka hljóðvalkostum", u"Hljóðfæraleikur", u"Spila — {count} spilanir", u"Líkar — {count}"),
	"it": (u"Torna alla creazione semplice", u"Apri o chiudi le opzioni di stile", u"Genera nuovi suggerimenti di stile", u"Apri o chiudi le opzioni audio", u"Strumentale", u"Riproduci — {count} riproduzioni", u"Mi piace — {count}"),
	"ja": (u"簡単作成に戻る", u"スタイルオプションを開くまたは閉じる", u"新しいスタイル候補を生成", u"オーディオオプションを開くまたは閉じる", u"インストゥルメンタル", u"再生 — {count}回", u"高評価 — {count}"),
	"ka": (u"მარტივ შექმნაზე დაბრუნება", u"სტილის პარამეტრების გახსნა ან დახურვა", u"სტილის ახალი შემოთავაზებების შექმნა", u"აუდიოს პარამეტრების გახსნა ან დახურვა", u"ინსტრუმენტული", u"დაკვრა — {count} მოსმენა", u"მოწონება — {count}"),
	"km": (u"ត្រឡប់ទៅការបង្កើតធម្មតា", u"បើក ឬបិទជម្រើសរចនាប័ទ្ម", u"បង្កើតសំណើរចនាប័ទ្មថ្មី", u"បើក ឬបិទជម្រើសអូឌីយ៉ូ", u"ភ្លេងឥតចម្រៀង", u"ចាក់ — {count} ដង", u"ចូលចិត្ត — {count}"),
	"kn": (u"ಸರಳ ರಚನೆಗೆ ಹಿಂತಿರುಗಿ", u"ಶೈಲಿ ಆಯ್ಕೆಗಳನ್ನು ತೆರೆಯಿರಿ ಅಥವಾ ಮುಚ್ಚಿರಿ", u"ಹೊಸ ಶೈಲಿ ಸಲಹೆಗಳನ್ನು ರಚಿಸಿ", u"ಆಡಿಯೊ ಆಯ್ಕೆಗಳನ್ನು ತೆರೆಯಿರಿ ಅಥವಾ ಮುಚ್ಚಿರಿ", u"ವಾದ್ಯ ಸಂಗೀತ", u"ಪ್ಲೇ — {count} ಬಾರಿ", u"ಇಷ್ಟ — {count}"),
	"ko": (u"간단한 만들기로 돌아가기", u"스타일 옵션 열기 또는 닫기", u"새 스타일 제안 생성", u"오디오 옵션 열기 또는 닫기", u"연주곡", u"재생 — {count}회", u"좋아요 — {count}"),
	"ky": (u"Жөнөкөй түзүүгө кайтуу", u"Стиль параметрлерин ачуу же жабуу", u"Жаңы стиль сунуштарын түзүү", u"Аудио параметрлерин ачуу же жабуу", u"Аспаптык", u"Ойнотуу — {count} жолу", u"Жакты — {count}"),
	"lb": (u"Zréck bei déi einfach Erstellung", u"Stiloptiounen op- oder zoumaachen", u"Nei Stilvirschléi generéieren", u"Audiooptiounen op- oder zoumaachen", u"Instrumental", u"Ofspillen — {count} Ofspillungen", u"Gefällt mir — {count}"),
	"lt": (u"Grįžti prie paprasto kūrimo", u"Atverti arba užverti stiliaus parinktis", u"Generuoti naujus stiliaus pasiūlymus", u"Atverti arba užverti garso parinktis", u"Instrumentinė", u"Leisti — {count} perklausų", u"Patinka — {count}"),
	"lv": (u"Atgriezties pie vienkāršās izveides", u"Atvērt vai aizvērt stila opcijas", u"Ģenerēt jaunus stila ieteikumus", u"Atvērt vai aizvērt audio opcijas", u"Instrumentāls", u"Atskaņot — {count} atskaņojumi", u"Patīk — {count}"),
	"mk": (u"Назад кон едноставно создавање", u"Отвори или затвори ги опциите за стил", u"Создај нови предлози за стил", u"Отвори или затвори ги опциите за аудио", u"Инструментална", u"Репродуцирај — {count} пати", u"Ми се допаѓа — {count}"),
	"mn": (u"Энгийн үүсгэлт рүү буцах", u"Загварын сонголтыг нээх эсвэл хаах", u"Шинэ загварын санал үүсгэх", u"Аудио сонголтыг нээх эсвэл хаах", u"Дан хөгжим", u"Тоглуулах — {count} удаа", u"Таалагдсан — {count}"),
	"mr": (u"सोप्या निर्मितीकडे परत जा", u"शैली पर्याय उघडा किंवा बंद करा", u"नवीन शैली सूचना तयार करा", u"ऑडिओ पर्याय उघडा किंवा बंद करा", u"वाद्यसंगीत", u"चालवा — {count} वेळा", u"आवडले — {count}"),
	"my": (u"ရိုးရှင်းစွာဖန်တီးခြင်းသို့ ပြန်သွားရန်", u"စတိုင်ရွေးချယ်စရာများကို ဖွင့်ရန် သို့မဟုတ် ပိတ်ရန်", u"စတိုင်အကြံပြုချက်အသစ်များ ဖန်တီးရန်", u"အသံရွေးချယ်စရာများကို ဖွင့်ရန် သို့မဟုတ် ပိတ်ရန်", u"တူရိယာသီးသန့်", u"ဖွင့်ရန် — {count} ကြိမ်", u"နှစ်သက်သည် — {count}"),
	"nb": (u"Tilbake til enkel opprettelse", u"Åpne eller lukk stilalternativer", u"Generer nye stilforslag", u"Åpne eller lukk lydalternativer", u"Instrumental", u"Spill av — {count} avspillinger", u"Liker — {count}"),
	"ne": (u"सरल सिर्जनामा फर्कनुहोस्", u"शैली विकल्प खोल्नुहोस् वा बन्द गर्नुहोस्", u"नयाँ शैली सुझावहरू सिर्जना गर्नुहोस्", u"अडियो विकल्प खोल्नुहोस् वा बन्द गर्नुहोस्", u"वाद्य सङ्गीत", u"बजाउनुहोस् — {count} पटक", u"मन पर्यो — {count}"),
	"nl": (u"Terug naar eenvoudig maken", u"Stijlopties openen of sluiten", u"Nieuwe stijlsuggesties genereren", u"Audio-opties openen of sluiten", u"Instrumentaal", u"Afspelen — {count} keer afgespeeld", u"Vind ik leuk — {count}"),
	"pa": (u"ਸਧਾਰਨ ਰਚਨਾ ਵੱਲ ਵਾਪਸ ਜਾਓ", u"ਸ਼ੈਲੀ ਚੋਣਾਂ ਖੋਲ੍ਹੋ ਜਾਂ ਬੰਦ ਕਰੋ", u"ਨਵੇਂ ਸ਼ੈਲੀ ਸੁਝਾਅ ਬਣਾਓ", u"ਆਡੀਓ ਚੋਣਾਂ ਖੋਲ੍ਹੋ ਜਾਂ ਬੰਦ ਕਰੋ", u"ਸਾਜ਼ੀ ਸੰਗੀਤ", u"ਚਲਾਓ — {count} ਵਾਰ", u"ਪਸੰਦ — {count}"),
	"pl": (u"Wróć do prostego tworzenia", u"Otwórz lub zamknij opcje stylu", u"Wygeneruj nowe propozycje stylu", u"Otwórz lub zamknij opcje dźwięku", u"Instrumentalny", u"Odtwórz — {count} odtworzeń", u"Lubię to — {count}"),
	"pt": (u"Voltar à criação simples", u"Abrir ou fechar opções de estilos", u"Gerar novas sugestões de estilos", u"Abrir ou fechar opções de áudio", u"Instrumental", u"Reproduzir — {count} reproduções", u"Gostei — {count} gostos"),
	"pt_BR": (u"Voltar à criação simples", u"Abrir ou fechar opções de estilos", u"Gerar novas sugestões de estilos", u"Abrir ou fechar opções de áudio", u"Instrumental", u"Reproduzir — {count} reproduções", u"Curtir — {count} curtidas"),
	"ro": (u"Înapoi la crearea simplă", u"Deschide sau închide opțiunile de stil", u"Generează sugestii noi de stil", u"Deschide sau închide opțiunile audio", u"Instrumental", u"Redare — {count} redări", u"Îmi place — {count}"),
	"ru": (u"Вернуться к простому созданию", u"Открыть или закрыть параметры стиля", u"Создать новые предложения стиля", u"Открыть или закрыть параметры звука", u"Инструментальная композиция", u"Воспроизвести — {count} прослушиваний", u"Нравится — {count}"),
	"sk": (u"Späť na jednoduché vytvorenie", u"Otvoriť alebo zavrieť možnosti štýlu", u"Vygenerovať nové návrhy štýlu", u"Otvoriť alebo zavrieť možnosti zvuku", u"Inštrumentálna", u"Prehrať — {count} prehratí", u"Páči sa mi — {count}"),
	"sl": (u"Nazaj na preprosto ustvarjanje", u"Odpri ali zapri možnosti sloga", u"Ustvari nove predloge slogov", u"Odpri ali zapri možnosti zvoka", u"Instrumental", u"Predvajaj — {count} predvajanj", u"Všeč mi je — {count}"),
	"sq": (u"Kthehu te krijimi i thjeshtë", u"Hap ose mbyll opsionet e stilit", u"Gjenero sugjerime të reja stili", u"Hap ose mbyll opsionet e audios", u"Instrumentale", u"Luaj — {count} dëgjime", u"Pëlqej — {count}"),
	"sr": (u"Nazad na jednostavno kreiranje", u"Otvori ili zatvori opcije stila", u"Generiši nove predloge stila", u"Otvori ili zatvori audio opcije", u"Instrumental", u"Pusti — {count} reprodukcija", u"Sviđa mi se — {count}"),
	"sv": (u"Tillbaka till enkelt skapande", u"Öppna eller stäng stilalternativ", u"Generera nya stilförslag", u"Öppna eller stäng ljudalternativ", u"Instrumental", u"Spela — {count} uppspelningar", u"Gilla — {count}"),
	"ta": (u"எளிய உருவாக்கத்திற்குத் திரும்பு", u"பாணி விருப்பங்களைத் திற அல்லது மூடு", u"புதிய பாணிப் பரிந்துரைகளை உருவாக்கு", u"ஒலி விருப்பங்களைத் திற அல்லது மூடு", u"கருவி இசை", u"இயக்கு — {count} முறை", u"விருப்பம் — {count}"),
	"te": (u"సరళ సృష్టికి తిరిగి వెళ్ళండి", u"శైలి ఎంపికలను తెరవండి లేదా మూసివేయండి", u"కొత్త శైలి సూచనలను రూపొందించండి", u"ఆడియో ఎంపికలను తెరవండి లేదా మూసివేయండి", u"వాయిద్య సంగీతం", u"ప్లే — {count} సార్లు", u"ఇష్టం — {count}"),
	"th": (u"กลับไปยังการสร้างแบบง่าย", u"เปิดหรือปิดตัวเลือกรูปแบบ", u"สร้างคำแนะนำรูปแบบใหม่", u"เปิดหรือปิดตัวเลือกเสียง", u"เพลงบรรเลง", u"เล่น — {count} ครั้ง", u"ถูกใจ — {count}"),
	"tr": (u"Basit oluşturmaya dön", u"Stil seçeneklerini aç veya kapat", u"Yeni stil önerileri oluştur", u"Ses seçeneklerini aç veya kapat", u"Enstrümantal", u"Oynat — {count} oynatma", u"Beğen — {count}"),
	"uk": (u"Повернутися до простого створення", u"Відкрити або закрити параметри стилю", u"Створити нові пропозиції стилю", u"Відкрити або закрити параметри аудіо", u"Інструментальна композиція", u"Відтворити — {count} прослуховувань", u"Подобається — {count}"),
	"ur": (u"سادہ تخلیق پر واپس جائیں", u"انداز کے اختیارات کھولیں یا بند کریں", u"نئے انداز کی تجاویز بنائیں", u"آڈیو کے اختیارات کھولیں یا بند کریں", u"سازینہ", u"چلائیں — {count} بار", u"پسند — {count}"),
	"vi": (u"Quay lại chế độ tạo đơn giản", u"Mở hoặc đóng tùy chọn phong cách", u"Tạo đề xuất phong cách mới", u"Mở hoặc đóng tùy chọn âm thanh", u"Nhạc không lời", u"Phát — {count} lượt", u"Thích — {count}"),
	"zh": (u"返回简单创作", u"打开或关闭风格选项", u"生成新的风格建议", u"打开或关闭音频选项", u"纯音乐", u"播放 — {count} 次", u"喜欢 — {count}"),
	"zh_HK": (u"返回簡易創作", u"開啟或關閉風格選項", u"產生新的風格建議", u"開啟或關閉音訊選項", u"純音樂", u"播放 — {count} 次", u"讚好 — {count}"),
	"zh_TW": (u"返回簡易創作", u"開啟或關閉風格選項", u"產生新的風格建議", u"開啟或關閉音訊選項", u"純音樂", u"播放 — {count} 次", u"喜歡 — {count}"),
}

KEY_INDEX = {
	"back": 0,
	"styles": 1,
	"refreshStyles": 2,
	"audio": 3,
	"instrumental": 4,
	"playCount": 5,
	"likeCount": 6,
}


def getLabel(language, key):
	language = (language or "en").replace("-", "_")
	baseLanguage = language.split("_", 1)[0]
	values = LABELS.get(language, LABELS.get(baseLanguage, LABELS["en"]))
	return values[KEY_INDEX[key]]
